[package]
version = "0.0.1"
authors = ["Pierre Baillet <pierre@baillet.name>"]

name = "small-deployer"
description = "A small git webhook server that can be used to trigger deploys. Send notification in slack."
repository = "https://github.com/octplane/small-deployer"

keywords = ["deploy", "github", "gitlab", "hook", "slack"]
readme = "README"

license= "MIT"
license-file= "LICENSE"

[dependencies]

rustc-serialize = "*"
time = "*"
hyper = "0.3.0"
slack-hook = "0.0.2"
